USE AdventureWorksLT2022
GO  


SELECT ProductID, ProductCategoryID, * FROM [SalesLT].[Product]
GO


BEGIN /*[SUBSTR] RETORNO UMA QUANTIDADE DE CARACTER APARTIR DE UMA POSIÇÃO EQUANTIDADE DETERMINADA*/
 
	DECLARE 
		@POSICAO_INICIAL	INT, 
		@QUNATIDADE_TOTAL	INT 

	SELECT	@POSICAO_INICIAL = 2,
			@QUNATIDADE_TOTAL = 3

	SELECT SUBSTRING(Name, @POSICAO_INICIAL, @QUNATIDADE_TOTAL), * FROM SalesLT.ProductCategory 

END
